apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-microservices-udagram-frontend
  labels:
    app: udagram-microservices-udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-microservices-udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-microservices-udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: ahmedmohsenyousef/udagram-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 8100