if: branch = master

language: node_js

node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  
  - cd reverse-proxy
  - docker build -t udagram-reverse-proxy .
  - docker tag udagram-reverse-proxy ahmedmohsenyousef/udagram-reverse-proxy:latest
  
  - cd ../udagram-api-feed/
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed ahmedmohsenyousef/udagram-api-feed:latest

  - cd ../udagram-api-users/
  - docker build -t udagram-api-users .
  - docker tag udagram-api-users ahmedmohsenyousef/udagram-api-users:latest

  - cd ../udagram-frontend/
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend ahmedmohsenyousef/udagram-frontend:latest


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ahmedmohsenyousef/udagram-reverse-proxy
  - docker push ahmedmohsenyousef/udagram-api-feed
  - docker push ahmedmohsenyousef/udagram-api-users
  - docker push ahmedmohsenyousef/udagram-frontend