apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-microservices-backend
  labels:
    app: udagram-microservices-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-microservices-backend
  template:
    metadata:
      labels:
        app: udagram-microservices-backend
    spec:
      containers:
      - name: udagram-api-users
        image: ahmedmohsenyousef/udagram-api-users
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m" 
        ports:
        - containerPort: 8082
        env:
        - name: POSTGRES_USERNAME
          value: ""
        - name: POSTGRES_PASSWORD
          value: ""
        - name: POSTGRES_HOST
          value: "udagramdev.clddvmsotzfa.us-east-1.rds.amazonaws.com"
        - name: POSTGRES_DB
          value: "udagram-microservices"
        - name: AWS_BUCKET
          value: "udagram-mohsen-dev-bucket"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_PROFILE
          value: "none"
        - name: JWT_SECRET
          value: ""
        - name: URL
          value: "*"
          
        
      - name: udagram-api-feed
        image: ahmedmohsenyousef/udagram-api-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m" 
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: secret-volume
          mountPath: "/root/.aws/"
          readOnly: true
        env:
        - name: POSTGRES_USERNAME
          value: ""
        - name: POSTGRES_PASSWORD
          value: ""
        - name: POSTGRES_HOST
          value: "udagramdev.clddvmsotzfa.us-east-1.rds.amazonaws.com"
        - name: POSTGRES_DB
          value: "udagram-microservices"
        - name: AWS_BUCKET
          value: "udagram-mohsen-dev-bucket"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_PROFILE
          value: "none"
        - name: JWT_SECRET
          value: ""
        - name: URL
          value: "*"
      volumes:
      - name: secret-volume
        secret:
          secretName: aws-secret