apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-microservices-udagram-api-users
  labels:
    app: udagram-microservices-udagram-api-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-microservices-udagram-api-users
  template:
    metadata:
      labels:
        app: udagram-microservices-udagram-api-users
    spec:
      containers:
      - name: udagram-api-users
        image: ahmedmohsenyousef/udagram-api-users
        imagePullPolicy: Always
        ports:
        - containerPort: 8082