apiVersion: v1
kind: Service
metadata:
  name: udagram-microservices
spec:
  selector:
    app: udagram-microservices-reverse-proxy
  ports:
    - name: backend-http
      protocol: TCP
      port: 8080
      targetPort: 8080
      
  type: LoadBalancer