apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-microservices-udagram-api-feed
  labels:
    app: udagram-microservices-udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-microservices-udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-microservices-udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: ahmedmohsenyousef/udagram-api-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 8081